apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharetrip
  namespace: sharetrip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sharetrip
  template:
    metadata:
      labels:
        app: sharetrip
    spec:
      containers:
        - name: sharetrip
          image: sharetrip/sharetrip:local
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sharetrip-config
            - secretRef:
                name: sharetrip-secret
