// Code generated by MockGen. DO NOT EDIT.
// Source: contract_client.go
//
// Generated by this command:
//
//	mockgen -source=contract_client.go -destination=mocks/contract_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "job4j_go_share_trip/internal/business/trip/entity"
	contract "job4j_go_share_trip/internal/clients/contract"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContractClient is a mock of ContractClient interface.
type MockContractClient struct {
	ctrl     *gomock.Controller
	recorder *MockContractClientMockRecorder
	isgomock struct{}
}

// MockContractClientMockRecorder is the mock recorder for MockContractClient.
type MockContractClientMockRecorder struct {
	mock *MockContractClient
}

// NewMockContractClient creates a new mock instance.
func NewMockContractClient(ctrl *gomock.Controller) *MockContractClient {
	mock := &MockContractClient{ctrl: ctrl}
	mock.recorder = &MockContractClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractClient) EXPECT() *MockContractClientMockRecorder {
	return m.recorder
}

// CheckService mocks base method.
func (m *MockContractClient) CheckService(ctx context.Context, companyID string, serviceCode entity.ServiceType) (contract.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckService", ctx, companyID, serviceCode)
	ret0, _ := ret[0].(contract.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckService indicates an expected call of CheckService.
func (mr *MockContractClientMockRecorder) CheckService(ctx, companyID, serviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckService", reflect.TypeOf((*MockContractClient)(nil).CheckService), ctx, companyID, serviceCode)
}
