services:
  postgres:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tracker
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  loki:
    image: grafana/loki:3.7.0
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: run /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ../logs:/var/log/myapp:ro
    depends_on:
      - loki
volumes:
  pgdata:
  loki_data:
  grafana_data:
